# config.yml
location: "/home/p3/IdeaProjects/Pdf_POC/src/main/resources/pdf_report"
reportName: "License Volume Statistics Report"
imagePath: "/home/p3/IdeaProjects/Pdf_POC/src/main/resources/Archon-Datastore rasterized.png"
