# config.yml
location: "C:\\Users\\P3INW82\\IdeaProjects\\Archon_Pdf_Poc\\src\\main\\resources\\pdf_report"
reportName: "Table Data Optimization Report"
imagePath: "C:\\Users\\P3INW82\\IdeaProjects\\Archon_Pdf_Poc\\src\\main\\resources\\Archon-Datastore rasterized.png"
