package com.p3solutions.archon_report_utility.constants;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class HeaderConstants {

    // Header Input
    public static final String GENERATED_BY = "Generated By\n";

    public static final String VIEW_ACTIVITY_SESSION_ID = "View Activity Session Id\n";

    public static final String REPORT_GENERATED_TIME = "Report Generated Time\n";

    // Header For Cell

    public static final String JOB_SUMMARY = "Job Summary";

    public static final String OBJECTIVE_HEADER = "Objective";

    public static final String ADDITIONAL_DETAILS = "Additional Details";


}
